# Generated by Django 3.0.3 on 2020-03-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='midyear_population',
        ),
    ]
